name: namgen tests
run-name: ${{ github.actor }} is running tests for namgen ğŸš€
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Test build in the repository
        run: |
          cd ${{ github.workspace }} && cmake . && make && sudo make install
      - name: Install Bats
        run: |
          sudo apt-get update && sudo apt-get -yqq install bats
      - name: Bats Test
        run: |
          cd ${{ github.workspace }} && bats -x test/full.bats 
      - run: echo "ğŸ This job's status is ${{ job.status }}."
